config/routes.rb
Rails.application.routes.draw do

  resources :ticket_items
  resources :tickets, only: [:index] do
    collection do
      get 'current'
      get 'confirm'
      post 'payment'
      get 'thank-you'
    end
  end

  resources :modifier_group_options
  resources :modifier_groups
  resources :items, only: [:index]

  devise_for :users, 
    path_names: 
    { sign_in: 'login', 
      sign_out: 'logout', 
      password: 'password', 
      confirmation: 'verification', 
      unlock: 'unblock', 
      registration: 'register', 
      sign_up: 'signup' 
  }, 
  controllers: {
    sessions: 'sessions'
  }

  devise_for :admins, :skip => [:registrations], path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', sign_up: 'signup' }

  as :admin do
    get 'admin/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admin/:id' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root "items#index"

  namespace :admin do
    resources :locations
    resources :tickets, only: [:index]
    resources :logs, only: [:index]
    resources :settings, except: [:show]
  end

end

app/models/location.rb
class Location
  include Mongoid::Document

  has_many :categories, dependent: :destroy

  field :omnivore_id, type: String
  field :name, type: String

  validates :omnivore_id, presence: true, uniqueness: true, blank: false
  validates :name, presence: true, uniqueness: true, blank: false

  def items
    self.categories.inject([]) {|items, cat| items + cat.items}
  end

  def modifier_groups
    self.items.inject([]) {|modifier_groups, item| modifier_groups + item.modifier_groups}
  end

  def get_data
    get_menu_category
    get_menu_items
    get_item_modifier_groups
    get_modifier_group_options
  end

  #Get location menu categories

  def get_menu_category
    require "rest_client"
    require "json"

    self.categories.update_all(still_present: false)
    response = RestClient.get("https://api.omnivore.io/0.1/locations/#{self.omnivore_id}/menu/categories", {:content_type => :json, :'Api-Key' => Setting.first.app_api_key})
    res = JSON.parse(response)
    res["_embedded"]["categories"].each do |category|
      cat = self.categories.where(omnivore_id: category["id"]).first_or_create
      cat.name = category["name"]
      cat.still_present = true
      cat.save
    end

    self.categories.where(still_present: false).destroy_all
  end

  def get_menu_items
    require "rest_client"
    require "json"

    self.categories.each do |category|
      category.items.update_all(still_present: false)

      response = RestClient.get("https://api.omnivore.io/0.1/locations/#{self.omnivore_id}/menu/categories/#{category.omnivore_id}/items", {:content_type => :json, :'Api-Key' => Setting.first.app_api_key})

      res = JSON.parse(response)

      res["_embedded"]["menu_items"].each do |item|
        i = category.items.where(omnivore_id: item["id"]).first_or_create
        i.name = item["name"]
        i.price = item["price"]
        i.in_stock = item["in_stock"]
        i.still_present = true
        i.save
      end

      category.items.where(still_present: false).destroy_all
    end

  end

  def get_item_modifier_groups
    self.items.each do |item|
      item.modifier_groups.update_all(still_present: false)

      response = RestClient.get("https://api.omnivore.io/0.1/locations/#{self.omnivore_id}/menu/items/#{item.omnivore_id}/modifier_groups/", {:content_type => :json, :'Api-Key' => Setting.first.app_api_key})
      res = JSON.parse(response)

      res["_embedded"]["modifier_groups"].each do |mg|
        mod_grp = item.modifier_groups.where(omnivore_id: mg["id"]).first_or_create
        mod_grp.name = mg["name"]
        mod_grp.required = mg["required"]
        mod_grp.maximum = mg["maximum"]
        mod_grp.minimum = mg["minimum"]
        mod_grp.still_present = true
        mod_grp.save
      end

      item.modifier_groups.where(still_present: false).destroy_all
    end
  end

  def get_modifier_group_options
    self.modifier_groups.each do |mg|
      mg.modifier_group_options.update_all(still_present: false)

      response = RestClient.get("https://api.omnivore.io/0.1/locations/#{self.omnivore_id}/menu/items/#{mg.item.omnivore_id}/modifier_groups/#{mg.omnivore_id}/modifiers", {:content_type => :json, :'Api-Key' => Setting.first.app_api_key})
      res = JSON.parse(response)

      res["_embedded"]["modifiers"].each do |option|
        opt = mg.modifier_group_options.where(omnivore_id: option["id"]).first_or_create
        opt.name = option["name"]
        opt.price_per_unit = option["price_per_unit"]
        opt.still_present = true
        opt.save
      end

      mg.modifier_group_options.where(still_present: false).destroy_all
    end
  end

end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  before_filter :authenticate_admin!
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  def index
    @locations = Location.all
  end

  # GET /locations/1
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    @location = Location.new(location_params)

    if @location.save
      redirect_to admin_locations_path, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to admin_locations_path, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy
    redirect_to admin_locations_path, notice: 'Location was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def location_params
      params.require(:location).permit(:name, :omnivore_id)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/admin/locations/_form.html.erb
<%= simple_form_for([:admin, @location]) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :omnivore_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "button small orange" %>
  </div>
<% end %>

app/views/admin/locations/edit.html.erb
<div class="small-12 columns">
  <h1>Edit</h1>
  <%= render 'form' %>
  <%= link_to 'Back', admin_locations_path %>
</div>

app/views/admin/locations/index.html.erb
<div class="small-12 columns">
<h1>Locations</h1>

<table>
  <thead>
    <tr>
      <th width="60%" class="text-center">Name</th>
      <th width="15%" class="text-center">Id</th>
      <th width="25%" class="text-center" colspan="2">Manage</th>
    </tr>
  </thead>

  <tbody>
    <% if @locations.length > 0 %>
    <% @locations.each do |location| %>
      <tr>
        <td><%= location.name %></td>
        <td class="text-center"><%= location.omnivore_id %></td>
        <td class="text-center"><%= link_to 'Edit', edit_admin_location_path(location) %></td>
        <td class="text-center"><%= link_to 'Destroy', admin_location_path(location), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  <% else %>
    <tr>
      <td>No locations found.</td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add New', new_admin_location_path, class: "button small orange" %>
</div>

app/views/admin/locations/new.html.erb
<div class="small-12 columns">
  <h1>Add New</h1>
  <%= render 'form' %>
  <%= link_to 'Back', admin_locations_path %>
</div>

app/views/admin/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @location.name %>
</p>

<p>
  <strong>Id:</strong>
  <%= @location.id %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>