config/routes.rb
Rails.application.routes.draw do

  resources :ticket_items
  resources :tickets, only: [:index] do
    collection do
      get 'current'
      get 'confirm'
      post 'payment'
      get 'thank-you'
    end
  end

  resources :modifier_group_options
  resources :modifier_groups
  resources :items, only: [:index]

  devise_for :users, 
    path_names: 
    { sign_in: 'login', 
      sign_out: 'logout', 
      password: 'password', 
      confirmation: 'verification', 
      unlock: 'unblock', 
      registration: 'register', 
      sign_up: 'signup' 
  }, 
  controllers: {
    sessions: 'sessions'
  }

  devise_for :admins, :skip => [:registrations], path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', sign_up: 'signup' }

  as :admin do
    get 'admin/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admin/:id' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root "items#index"

  namespace :admin do
    resources :locations
    resources :tickets, only: [:index]
    resources :logs, only: [:index]
    resources :settings, except: [:show]
  end

end

app/models/ticket.rb
class Ticket
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :user
  has_many :ticket_items

  field :status, type: String, default: "Draft"
  field :omnivore_id, type: String

end

app/controllers/admin/tickets_controller.rb
class Admin::TicketsController < ApplicationController
  def index
    @tickets = Ticket.all.where(status: "Complete").order(updated_at: :desc)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_filter :authenticate_user!

  # GET /tickets
  def index
    @tickets = current_user.tickets.where(status: "Complete").order(updated_at: :desc)
  end

  def current
    @ticket = current_ticket
  end

  def payment
    require 'rest_client'
    require "json"

    items = []

    current_ticket.ticket_items.each do |ticket_item|
      item = {
        menu_item: ticket_item.omnivore_id,
        quantity: ticket_item.quantity
      }

      items << item
    end

    payload = {
      employee: "xET7jTqk",
      order_type: "jLTqoTba",
      revenue_center: "gdTMpTKz"
    }

    # Open a new ticket
    response = RestClient.post(
      "https://api.omnivore.io/0.1/locations/#{Location.first.omnivore_id}/tickets",
      payload.to_json, {:content_type => :json, :'Api-Key' => Setting.first.app_api_key}
    )

    @response = JSON.parse(response)

    # Add ticket items to ticket
    RestClient.post(
      "https://api.omnivore.io/0.1/locations/#{Location.first.omnivore_id}/tickets/#{@response['id']}/items",
      items.to_json,
      {:content_type => :json, :'Api-Key' => Setting.first.app_api_key}
    )

    payment = {
      type: "card_not_present",
      amount: (current_ticket.ticket_items.inject(0) { |sum, ti| sum + (ti.price * ti.quantity) }),
      tip: (params[:tip]*100).to_i,
      card_info: {
        exp_month: params[:date][:expiration_month].to_i,
        exp_year: params[:date][:expiration_year].to_i,
        cvc2: params[:cvc],
        number: params[:card_number]
      }
    }

    # Send payment info
    begin
      payment_response = RestClient.post(
        "https://api.omnivore.io/0.1/locations/#{Location.first.omnivore_id}/tickets/#{@response['id']}/payments/",
        payment.to_json,
        {:content_type => :json, :'Api-Key' => Setting.first.app_api_key}
      )
    rescue
      redirect_to current_tickets_url, alert: "Payment could not be processed. Please check payment data and try again." and return
    end

    current_ticket.update_attributes(
      status: "Complete",
      user: current_user,
      omnivore_id: @response["id"]
    )

    Log.create(type: "Ticket", description: "User with email #{current_user.email} paid for ticket #{current_ticket._id}. Omnivore id is #{@response["id"]}")

    @payment_response = JSON.parse(payment_response)

    session[:ticket_id] = nil

  end

  def confirm

  end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/confirm.html.erb
<div class="small-12 columns">
  <h1>Make Payment</h1>
  <div class="row">
    <div class="small-6 columns">
      <%= form_tag payment_tickets_path, method: :post do %>
        <div class="row">
          <div class="small-12 medium-6 columns">
            <%= label_tag "amount", "Amount ($)" %>
            <%= text_field_tag "amount", current_ticket.ticket_items.inject(0) { |sum, ti| sum + ((ti.price * ti.quantity).to_f/100).round(2) }, disabled: true %>
          </div>
          <div class="small-12 medium-6 columns">
            <%= label_tag "tip", "Tip ($)" %>
            <%= number_field_tag "tip", 0 %>
          </div>
        </div>
        <%= label_tag "card_number",'Card Number' %>
        <%= text_field_tag "card_number", nil, maxlength: "16", required: true %>

        <div class="row">
          <div class="small-12 medium-6 columns">
            <%= label_tag "expiration_month", 'Expiration month' %>
            <%= select_month nil, { use_month_numbers: true, field_name: "expiration_month", include_blank: true }, { required: true } %>
          </div>

          <div class="small-12 medium-6 columns">
            <%= label_tag "expiration_year", 'Expiration year' %>
            <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year + 10, field_name: "expiration_year", include_blank: true }, { required: true } %>
          </div>
        </div>
        <div class="row">
          <div class="small-12 medium-6 columns">
            <%= label_tag "cvc", "CVC2" %>
            <%= text_field_tag "cvc", nil, required: true %>
          </div>
        </div>
        <%= submit_tag "Make Payment", class: "button small success" %>
        <br>
        <%= link_to "back", tickets_path %>
      <% end %>
    </div>
  </div>
</div>

app/views/tickets/current.html.erb
<div class="small-12 columns">
  <h1>Ticket</h1>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th class="text-center">Price ($)</th>
        <th class="text-center">Quantity</th>
        <th class="text-center">Total Price ($)</td>
        <th class="text-center">Manage</td>
      </tr>
    </thead>

    <tbody>
      <% current_ticket.ticket_items.each do |ticket_item| %>
        <tr>
          <td><%= ticket_item.name %></td>
          <td class="text-center"><%= (ticket_item.price.to_f/100).round(2) %></td>
          <%= form_tag ticket_item_path(ticket_item), method: :put do  %>
            <td class="text-center">
              <div class="row">
                <div class="small-6 small-offset-3 columns">
                  <%= number_field_tag "ticket_item[quantity]", ticket_item.quantity %></td>
                </div>
              </div>
              <td class="text-center"><%= ((ticket_item.price.to_f/100)*ticket_item.quantity).round(2) %></td>
              <td class="text-center">
                <%= submit_tag "Update", class: "button tiny" %>
              <% end %>
              <%= link_to '<i class="fa fa-times"></i>'.html_safe, ticket_item_path(ticket_item._id), method: :delete, data: {confirm: "Are you sure?"}, class: "button tiny alert" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <p>Ticket Total ($): <%= current_ticket.ticket_items.inject(0) { |sum, ti| sum + ((ti.price * ti.quantity).to_f/100).round(2) } %></p>
  <%= link_to "Confirm", confirm_tickets_url, class: "button small" %>
</div>

app/views/tickets/index.html.erb
<div class="small-12 columns">
  <table>
    <thead>
      <tr>
        <th width="20%" class="text-center">Date</th>
        <th width="20%" class="text-center">Confirmation ID</th>
        <th width="40%" class="text-center">Items</th>
        <th width="20%" class="text-center">Total ($)</th>
      </tr>
    </thead>
    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td class="text-center"><%= ticket.updated_at.strftime("%F") %></td>
          <td class="text-center"><%= ticket.omnivore_id %></td>
          <td class="text-center">
            <% ticket.ticket_items.each do |item| %>
              <%= "#{item.name} - #{item.quantity}" %>
              <br>
            <% end %>
          </td>
          <td class="text-center"><%= ticket.ticket_items.inject(0) { |sum, ti| sum + ((ti.price * ti.quantity).to_f/100).round(2) } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/tickets/payment.html.erb
<div class="small-12 columns">
  <p><%= "Thank you. Your ticket has been accepted and the ticket id is #{@response['id']}." %></p>
  <p><%= link_to "View previous tickets", tickets_path %></p>
</div>