config/routes.rb
Rails.application.routes.draw do

  resources :ticket_items
  resources :tickets, only: [:index] do
    collection do
      get 'current'
      get 'confirm'
      post 'payment'
      get 'thank-you'
    end
  end

  resources :modifier_group_options
  resources :modifier_groups
  resources :items, only: [:index]

  devise_for :users, 
    path_names: 
    { sign_in: 'login', 
      sign_out: 'logout', 
      password: 'password', 
      confirmation: 'verification', 
      unlock: 'unblock', 
      registration: 'register', 
      sign_up: 'signup' 
  }, 
  controllers: {
    sessions: 'sessions'
  }

  devise_for :admins, :skip => [:registrations], path: "admin", path_names: { sign_in: 'login', sign_out: 'logout', password: 'password', confirmation: 'verification', unlock: 'unblock', sign_up: 'signup' }

  as :admin do
    get 'admin/edit' => 'devise/registrations#edit', :as => 'edit_admin_registration'
    put 'admin/:id' => 'devise/registrations#update', :as => 'admin_registration'
  end

  root "items#index"

  namespace :admin do
    resources :locations
    resources :tickets, only: [:index]
    resources :logs, only: [:index]
    resources :settings, except: [:show]
  end

end

app/views/layouts/_alert_notice.html.erb
<% if !Setting.first.present? || !Setting.first.app_api_key.present? %>
  <% if admin_signed_in? %>
    <% flash[:alert] = "No API key found. Go to Manage > Setting to add one." %>
  <% end %>
<% end %>

<% if alert %>
  <div data-alert class="alert-box alert">
    <%= alert %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

<% if notice %>
  <div data-alert class="alert-box info">
    <%= notice %>
    <a href="#" class="close">&times;</a>
  </div>
<% end %>

app/views/layouts/_top_menu.html.erb
<nav class="top-bar" data-topbar role="navigation">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to app_name, root_url %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <li><%= link_to "Menu", items_path %></li>
      <li class="divider"></li>
      <li><%= link_to "Ticket (#{current_ticket.ticket_items.length.to_i})", current_tickets_path %></li>
      <li class="divider"></li>
      <% unless user_signed_in? || admin_signed_in? %>
        <li><%= link_to "Sign in", new_user_session_path, class: "" %></li>
        <li class="divider"></li>
      <% end %>
      <% if user_signed_in? %>
        <li class="has-dropdown">
          <a href="#"><%= current_user.email %></a>
          <ul class="dropdown">
            <li><%= link_to "Previous Tickets", tickets_path %></li>
            <li><%= link_to "Account", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
        <li class="divider"></li>
      <% end %>

      <% if admin_signed_in? %>
        <li class="has-dropdown">
          <a href="#">Manage</a>
          <ul class="dropdown">
            <li><%= link_to "Locations", admin_locations_path %></li>
            <li><%= link_to "Tickets", admin_tickets_path %></li>
            <li><%= link_to "Setting", admin_settings_path %></li>
            <li><%= link_to "Logs", admin_logs_path %></li>
          </ul>
        </li>
        <li class="divider"></li>

        <li class="has-dropdown">
          <a href="#"><%= current_admin.email %></a>
          <ul class="dropdown">
            <li><%= link_to "Account", edit_admin_registration_path %></li>
            <li><%= link_to "Log out", destroy_admin_session_path, method: :delete %></li>
          </ul>
        </li>
        <li class="divider"></li>
      <% end %>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : app_name %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= favicon_link_tag("favicon.png") %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row container">
      <%= render "layouts/top_menu" %>
      <%= render "layouts/alert_notice" %>
      <div class="content">
        <%= yield %>
      </div>
    </div>
    <div class="copyright">
      <p class="text-center"><%= "&copy; #{Date.today.year} #{app_name}. All rights reserved.".html_safe %></p>
    </div>
  </body>
</html>